version: 2

jobs:
  lint_and_test:
    docker:
      - image: hustleinc/ci-base:21
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install --no-progress
      - run:
          name: Run Tests
          command: npm test

workflows:
  version: 2
  hustle_workflow:
    jobs:
      - lint_and_test
